### ISSUE TITLE
Normalized probabilities: only 1.0 in output values

### ISSUE THREAD

**Issue by aleksandra-miletic** [adbar/py3langid#6]
Hi Adrien, 

I am currently testing py3langid and I noticed something strange: the normalized probability values in the output are systematically 1.0. I tested texts of different lengths (1 word to several paragraphs) in different languages. I'm using it with Python. Is this something you noticed before?

Thanks,
Aleksandra

**Comment by adbar** [comment]
Hi @aleksandra-miletic, thanks for your feedback. You're right, this is a bug.

I changed the formula to normalize probabilities along the way and apparently didn't check it properly.

The change in numpy data type also affects things a bit, and I didn't implement the possibility to write `classify(self, datatype='uint32')` although I wrote such an example in the readme... I'm going to fix this.

**Comment by aleksandra-miletic** [comment]
Great, thank you!
